// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PendataanPerangkat;

#nullable disable

namespace PendataanPerangkat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707030309_TambahTabelKategori")]
    partial class TambahTabelKategori
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PendataanPerangkat.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaKategori")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("PendataanPerangkat.Model.Perangkat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MerkBarang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spesifikasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Perangkats");
                });

            modelBuilder.Entity("PendataanPerangkat.Model.Perangkat", b =>
                {
                    b.HasOne("PendataanPerangkat.Kategori", "Kategori")
                        .WithMany("Perangkats")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("PendataanPerangkat.Kategori", b =>
                {
                    b.Navigation("Perangkats");
                });
#pragma warning restore 612, 618
        }
    }
}
