// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PendataanPerangkat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706035355_TambahStokPerangkat")]
    partial class TambahStokPerangkat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Perangkat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MerkBarang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spesifikasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Perangkats");
                });
#pragma warning restore 612, 618
        }
    }
}
